include:
  - project: 'IFHT/gitlab-ci-templates'
    file: '/python-package.yml'

variables:
  BUILD_REQUIRE: cython ortools

pytest:
  extends: .pytest

pylint:
  extends: .pylint

build_dist_3.6:
  extends: .build_dist
  image: python:3.6

build_dist_3.7:
  extends: .build_dist
  image: python:3.7

build_dist_ppc_3.6:
  extends: .build_dist
  image: $CI_REGISTRY/docker/devpi-builder:3.6-ubuntu-ppc
  allow_failure: true

build_dist_ppc_3.7:
  extends: .build_dist
  image: $CI_REGISTRY/docker/devpi-builder:3.7-ubuntu-ppc
  allow_failure: true

release_dist:
  extends: .release_dist
